### ISSUE TITLE
Fail to select JTable Cell - InvalidCellException

### ISSUE THREAD

**Issue by ghost** [robotframework/SwingLibrary#115]
Hello,

I am having a problem with **Click On Table Cell** as this keyword doesn't click on the table (JTable) cell.

I am passing the correct row (verified with static value as well) for selection but not sure what else I am missing.

Below is my code:

${row} = Find Table Row With Subtext ${TABLE_NAME} ${elementName} ${EMPTY}

Click On Table Cell ${TABLE_NAME} ${row}${TABLE_COLUMN_ID} ${SINGLE_CLICK_COUNT}  
(I have tried passing Table name as well as with table ID)

Can anyone please help me with this?

**Comment by sriharshahonne** [comment]
Below exception is observed.

Click On Table Cell ${TABLE_NAME}, ${row}, ${TABLE_COLUMN_ID}, ${SINGLE_CLICK_COUNT}

Documentation:
Clicks on a cell in a table, optionally using click count, a specific mouse button and keyboard modifiers.
Start / End / Elapsed:
20180921 17:15:41.582 / 20180921 17:15:41.590 / 00:00:00.008
17:15:41.582
TRACE
Arguments: [ '0' | 0 | '1' | '1' ]

17:15:41.590
FAIL
org.robotframework.swing.table.InvalidCellException: The specified table cell (row: 0, column: 1) is invalid.

17:15:41.590
DEBUG
org.robotframework.swing.table.InvalidCellException: The specified table cell (row: 0, column: 1) is invalid.
at org.robotframework.swing.table.TableOperator.findCell(TableOperator.java:227)
at org.robotframework.swing.table.TableOperator.findCell(TableOperator.java:220)
at org.robotframework.swing.table.TableOperator.clickOnCell(TableOperator.java:257)
at org.robotframework.swing.keyword.table.TableKeywords.clickOnTableCell(TableKeywords.java:403)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.robotframework.javalib.reflection.KeywordInvoker.invoke(KeywordInvoker.java:50)
at org.robotframework.javalib.beans.annotation.AnnotationKeywordExtractor$1.execute(AnnotationKeywordExtractor.java:62)
at org.robotframework.javalib.library.KeywordFactoryBasedLibrary.runKeyword(KeywordFactoryBasedLibrary.java:37)
at org.robotframework.javalib.library.AnnotationLibrary.runKeyword(AnnotationLibrary.java:81)
at org.robotframework.swing.SwingLibrary.runKeyword(SwingLibrary.java:133)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.robotframework.remoteserver.library.DynamicApiRemoteLibrary.runKeyword(DynamicApiRemoteLibrary.java:65)
at org.robotframework.remoteserver.servlet.ServerMethods.run_keyword(ServerMethods.java:90)
at org.robotframework.remoteserver.servlet.ServerMethods.run_keyword(ServerMethods.java:154)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.robotframework.remoteswinglibrary.org.apache.xmlrpc.server.ReflectiveXmlRpcHandler.invoke(ReflectiveXmlRpcHandler.java:115)
at org.robotframework.remoteswinglibrary.org.apache.xmlrpc.server.ReflectiveXmlRpcHandler.execute(ReflectiveXmlRpcHandler.java:106)
at org.robotframework.remoteswinglibrary.org.apache.xmlrpc.server.XmlRpcServerWorker.execute(XmlRpcServerWorker.java:46)
at org.robotframework.remoteswinglibrary.org.apache.xmlrpc.server.XmlRpcServer.execute(XmlRpcServer.java:86)
at org.robotframework.remoteswinglibrary.org.apache.xmlrpc.server.XmlRpcStreamServer.execute(XmlRpcStreamServer.java:200)
at org.robotframework.remoteswinglibrary.org.apache.xmlrpc.webserver.XmlRpcServletServer.execute(XmlRpcServletServer.java:112)
at org.robotframework.remoteswinglibrary.org.apache.xmlrpc.webserver.XmlRpcServlet.doPost(XmlRpcServlet.java:196)
at org.robotframework.remoteserver.servlet.RemoteServerServlet.doPost(RemoteServerServlet.java:122)
at org.robotframework.remoteswinglibrary.javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
at org.robotframework.remoteserver.servlet.RemoteServerServlet.service(RemoteServerServlet.java:102)
at org.robotframework.remoteswinglibrary.javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:565)
at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:479)
at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1031)
at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:406)
at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:965)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)
at org.eclipse.jetty.server.Server.handle(Server.java:348)
at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:452)
at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:894)
at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:948)
at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:851)
at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:77)
at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:606)
at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:46)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:603)
at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:538)
at java.lang.Thread.run(Unknown Source)

**Comment by badari412** [comment]
"InvalidCellException" denotes that the you are looking for a non existent cell. The error has nothing to do with the name or id of the table. You would have got a different exception if the table didn't exist. Are you sure the table is not empty?

**Comment by mihaiparvu** [comment]
Closing due to inactivity.
