### ISSUE TITLE
'Get Table Column Values' throws RuntimeException when Table is empty

### ISSUE THREAD

**Issue by langacker** [robotframework/SwingLibrary#54]
As in title, bare Runtime Exception is thrown, this is unexpected and undocumented behaviour. It seems that core cause is that org.netbeans.jemmy.operators.JTableOperator.getRowCount() returns -1 when table has no rows instead of 0.
Also keyword Get Table Row Count behaves incorrectly and returns -1 for empty table.

Excerpt from log:

${imported_files} = SwingLibrary.Get Table Column Values 0, Dateien
...
FAIL    RuntimeException
14:30:19.108    DEBUG   java.lang.RuntimeException
    at org.robotframework.javalib.library.AnnotationLibrary.retrieveInnerException(AnnotationLibrary.java:148)
    at org.robotframework.javalib.library.AnnotationLibrary.runKeyword(AnnotationLibrary.java:130)
    at org.robotframework.swing.SwingLibrary.runKeyword(SwingLibrary.java:112)
.....
Caused by: java.lang.NegativeArraySizeException
    at org.robotframework.swing.table.TableOperator.getColumnValues(TableOperator.java:186)

**Comment by cristii006** [comment]
Hi @langacker ,

I am not able to reproduce the error you reported, it was probably solved since then outside of SwingLibrary, and we couldn't find any scenario in which -1 is transmitted to SwingLibrary. 
When the table is empty the `Get Row Count` keyword returns the expected output i.e. 0.  There is no observed problem with `Get Table Column Values` either.

BR,
Cristi

**Comment by langacker** [comment]
It's a refreshing experience to have your 5 years old ticket answered, being several projects and employees further ;). Nevertheless, thanks for care!
